export enum Collection {
  "Lootbox" = "lootbox",
  "User" = "user",
  "Wallet" = "wallet",
  "Tournament" = "tournament",
  "PartyBasket" = "party-basket",
  "WhitelistSignature" = "whitelist-signature",
  "Stream" = "stream",
  "Referral" = "referral",
  "Claim" = "claim",
  "Ad" = "ad",
  "Creative" = "creative",
  "AdEvent" = "ad-event",
  "Offer" = "offer",
  "Advertiser" = "advertiser",
  "Affiliate" = "affiliate",
  "Memo" = "memo",
  "Conquest" = "conquest",
}
